language: node_js
node_js:
  - 8
cache: npm
script:
  - npm run lint
  - npm run test
  - npm run build api
  - npm run build:ssr
addons:
  ssh_known_hosts: "slackmap.com"
before_deploy:
  - openssl aes-256-cbc -K $encrypted_430392f7e341_key -iv $encrypted_430392f7e341_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - chmod +x ./tools/scripts/deploy-test.sh
  - git config credential.helper "store --file=.git/credentials"; echo "https://${GH_TOKEN}:@github.com" > .git/credentials 2>/dev/null
  - git config --global user.email "travisci@slackmap.com"
  - git config --global user.name "TravisCI"
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./tools/scripts/deploy-test.sh
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: bash ./tools/scripts/deploy-prod.sh
    on:
      branch: master
notifications:
  email: false
